// <auto-generated />
using System;
using InterviewCoach.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InterviewCoach.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261003014851_AddResumeTopics")]
    partial class AddResumeTopics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("InterviewCoach.Core.Models.CandidateProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JobRole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResumeText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Seniority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("Profiles", (string)null);
                });

            modelBuilder.Entity("InterviewCoach.Infrastructure.Persistence.JdTechnologiesEntity", b =>
                {
                    b.Property<string>("Fingerprint")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TechnologiesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Fingerprint");

                    b.ToTable("JdTechnologies", (string)null);
                });

            modelBuilder.Entity("InterviewCoach.Infrastructure.Persistence.LearnHistoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoachJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFollowUp")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsGeneral")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentQuestion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestionKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Seniority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Technology")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TimesSeen")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LastSeenAt");

                    b.HasIndex("QuestionKey", "ParentKey", "IsGeneral", "ProfileName")
                        .IsUnique();

                    b.ToTable("LearnHistory", (string)null);
                });

            modelBuilder.Entity("InterviewCoach.Infrastructure.Persistence.ResumeTopicsEntity", b =>
                {
                    b.Property<string>("Fingerprint")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TopicsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Fingerprint");

                    b.ToTable("ResumeTopics", (string)null);
                });

            modelBuilder.Entity("InterviewCoach.Infrastructure.Persistence.TechAnswerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnswerWords")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoachJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TechQuestionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TechQuestionId", "AnswerWords")
                        .IsUnique();

                    b.ToTable("TechAnswers", (string)null);
                });

            modelBuilder.Entity("InterviewCoach.Infrastructure.Persistence.TechQuestionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Focus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestionKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Seniority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Technology")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TechnologyKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TechnologyKey", "Seniority", "QuestionKey")
                        .IsUnique();

                    b.ToTable("TechQuestions", (string)null);
                });

            modelBuilder.Entity("InterviewCoach.Infrastructure.Persistence.TechAnswerEntity", b =>
                {
                    b.HasOne("InterviewCoach.Infrastructure.Persistence.TechQuestionEntity", null)
                        .WithMany("Answers")
                        .HasForeignKey("TechQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InterviewCoach.Infrastructure.Persistence.TechQuestionEntity", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
