// <auto-generated />
using System;
using InterviewCoach.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InterviewCoach.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("InterviewCoach.Core.Models.CandidateProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JobRole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResumeText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Seniority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("Profiles", (string)null);
                });

            modelBuilder.Entity("InterviewCoach.Infrastructure.Persistence.JdTechnologiesEntity", b =>
                {
                    b.Property<string>("Fingerprint")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TechnologiesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Fingerprint");

                    b.ToTable("JdTechnologies", (string)null);
                });

            modelBuilder.Entity("InterviewCoach.Infrastructure.Persistence.TechAnswerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnswerWords")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoachJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TechQuestionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TechQuestionId", "AnswerWords")
                        .IsUnique();

                    b.ToTable("TechAnswers", (string)null);
                });

            modelBuilder.Entity("InterviewCoach.Infrastructure.Persistence.TechQuestionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Focus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestionKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Seniority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Technology")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TechnologyKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TechnologyKey", "Seniority", "QuestionKey")
                        .IsUnique();

                    b.ToTable("TechQuestions", (string)null);
                });

            modelBuilder.Entity("InterviewCoach.Infrastructure.Persistence.TechAnswerEntity", b =>
                {
                    b.HasOne("InterviewCoach.Infrastructure.Persistence.TechQuestionEntity", null)
                        .WithMany("Answers")
                        .HasForeignKey("TechQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InterviewCoach.Infrastructure.Persistence.TechQuestionEntity", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
